import asyncio
import os
import shutil
import time
from playwright.async_api import async_playwright

APP_URL = "https://chicago-parking-frontend-466731583426.us-central1.run.app"
ARTIFACTS_DIR = "/config/.gemini/antigravity/brain/c02afe69-ca6d-4ec3-86db-29e79e457b94"
VIDEO_TEMP_DIR = os.path.join(ARTIFACTS_DIR, "video_temp")
FINAL_VIDEO_MP4 = os.path.join(ARTIFACTS_DIR, "demo_video.mp4")

os.makedirs(VIDEO_TEMP_DIR, exist_ok=True)

async def record_demo():
    print("🎬 Starting Playwright demo recording...")
    async with async_playwright() as p:
        browser = await p.chromium.launch(
            headless=True,
            args=["--no-sandbox", "--disable-setuid-sandbox"]
        )
        context = await browser.new_context(
            viewport={"width": 1280, "height": 800},
            record_video_dir=VIDEO_TEMP_DIR,
            record_video_size={"width": 1280, "height": 800}
        )
        page = await context.new_page()

        print(f"🌐 Navigating to {APP_URL}...")
        await page.goto(APP_URL, wait_until="networkidle")
        await page.wait_for_timeout(3000)

        # Prompt 1: Core Parking Restriction & Street Cross-Section Query
        prompt_1 = "I parked at 1200 N Milwaukee Ave"
        print(f"💬 Sending Prompt 1: '{prompt_1}'")
        await page.fill("input#input", prompt_1)
        await page.wait_for_timeout(1000)
        await page.click("button[type='submit']")

        # Wait for agent response and generated image to appear
        print("⏳ Waiting for agent response and 80s street diagram...")
        await page.wait_for_selector(".generated-img-card img", timeout=45000)
        await page.wait_for_timeout(5000)

        # Scroll to ensure image is visible
        await page.evaluate("window.scrollTo(0, document.body.scrollHeight)")
        await page.wait_for_timeout(3000)

        # Prompt 2: Database Write + AI Image Generation
        prompt_2 = "Save this spot as my primary vehicle location and check 2400 N Clark St"
        print(f"💬 Sending Prompt 2: '{prompt_2}'")
        await page.fill("input#input", prompt_2)
        await page.wait_for_timeout(1500)
        await page.click("button[type='submit']")

        print("⏳ Waiting for response and second 80s street diagram...")
        await page.wait_for_selector(".msg:nth-child(4) .generated-img-card img", timeout=45000)
        await page.wait_for_timeout(6000)

        await page.evaluate("window.scrollTo(0, document.body.scrollHeight)")
        await page.wait_for_timeout(4000)

        await page.close()
        await context.close()
        await browser.close()

    print("🎥 Recording complete! Locating recorded video...")
    video_files = [f for f in os.listdir(VIDEO_TEMP_DIR) if f.endswith(".webm")]
    if not video_files:
        raise RuntimeError("No video file generated by Playwright!")

    recorded_webm = os.path.join(VIDEO_TEMP_DIR, video_files[0])
    print(f"Converting {recorded_webm} to {FINAL_VIDEO_MP4} using ffmpeg...")
    
    # Convert webm to mp4 using ffmpeg
    cmd = f"ffmpeg -y -i '{recorded_webm}' -c:v libx264 -pix_fmt yuv420p '{FINAL_VIDEO_MP4}'"
    os.system(cmd)
    
    shutil.rmtree(VIDEO_TEMP_DIR, ignore_errors=True)
    print(f"✅ Demo video recorded and saved to {FINAL_VIDEO_MP4}!")

if __name__ == "__main__":
    asyncio.run(record_demo())
